{% set name = "repodeploy" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/SimonBoothroyd/repodeploy.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - repodeploy

about:
  home: https://github.com/SimonBoothroyd/repodeploy
  license: MIT
  license_file:
    - LICENSE
  summary: Proof-of-concept for deploying packages to conda without a feedstock
  description: |
    Proof-of-concept for deploying packages to conda without a feedstock
  doc_url: https://github.com/SimonBoothroyd/repodeploy
  dev_url: https://github.com/SimonBoothroyd/repodeploy

extra:
  recipe-maintainers:
    - simonboothroyd